# Generated by Django 4.1.2 on 2022-10-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootuser',
            name='sex',
            field=models.IntegerField(choices=[(0, 'MALE'), (1, 'FEMALE'), (2, 'OTHER')]),
        ),
    ]
