# Generated by Django 4.1.2 on 2022-10-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_rootuser_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootuser',
            name='sex',
            field=models.IntegerField(choices=[(0, 'MALE'), (1, 'FEMALE'), (2, 'OTHER')], null=True),
        ),
    ]
