# Generated by Django 4.1.2 on 2022-10-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='feature_image',
            field=models.FileField(null=True, upload_to='product/feature-image/'),
        ),
    ]
